/* Generated By:JavaCC: Do not edit this line. WSParserConstants.java */
package jp.gr.java_conf.mizu.es.ws.parser;

public interface WSParserConstants {

  int EOF = 0;
  int COMMENT = 1;
  int S = 2;
  int T = 3;
  int L = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
